### PR TITLE
Filter out future-dated sensor events

### LINKED ISSUE #2087: Dev Feature - upload sensor start reported as future date
**Describe the bug**
Sometime in the recent past, the sensor start upload to Nightscout was uploaded with a future start.

**Attach an Issue Report**
see attached zip file with Loop Report and Critical logs zipped togerher.

**Expected behavior**
The Nightscout CGM Sensor Start should be correct.

**Screenshots**
Future dates were showing in Nightscout - once deleted the SAGE is correctly displayed,
IMG_6073

**Phone**
 - Hardware: iPhone 11 pro
 - OS Version: 16.7

**Loop Version**
 - Version Number: 3.3.0, commit 9a3666d
 - Repo: LoopKit/LoopWorkspace
 - Dexcom G6 CGM
 - DASH pod

[03-sensor-start-in-future-treatment-from-loop.zip](https://github.com/LoopKit/Loop/files/12919652/03-sensor-start-in-future-treatment-from-loop.zip)

**Additional context**
Several others have posted this happened to them and they had future treatments in Nightscout.

### PR DESCRIPTION
**Pull request by bjorkert**
Implemented a filter in TransmitterManager to exclude future-dated sensor events before sending to Nightscout. The solution has been successfully tested with a real sensor.

Resolves https://github.com/LoopKit/Loop/issues/2087

### CODE REVIEW

**Comment by marionbarker** [comment]
The person who tested this uses G6 sensors with Loop-dev.
* The SAGE pill was not poplulated
* They first examined Nightscout for future dates, see graphic below
* After removing future dates in Nightscout, the SAGE pill was populated with the age of the sensor

Nightscout-Before-PR

After applying the code from this PR, a new sensor was started and the SAGE pill was populated without needing to remove future dates from Nightscout.

SAGE-works-with-PR

**Comment by marionbarker** [comment]
@ps2 Please respond. This is a work-around for the root cause, but it does work to provide SAGE correctly for Loop users with Nightscout.

File: CGMBLEKit/TransmitterManager.swift [hunk 1]
```diff
@@ -335,6 +335,11 @@ public class TransmitterManager: TransmitterDelegate {
             ))
         }
 
+        // Filter out future-dated events
+        events = events.filter { event in
```
Comment (ps2) [inline CGMBLEKit/TransmitterManager.swift:340]: This is not fixing the underlying problem (incorrect parsing of message data earlier in the process).  Please add a comment that this is a stopgap fix for the issue (https://github.com/LoopKit/Loop/issues/2087) and add an error level log here that includes a string description of the `glucose` object.

**Review by ps2 — CHANGES_REQUESTED** [review]

**Review by ps2 — APPROVED** [review]

**Comment by ps2** [comment]
Thanks!
